=== vkrishnanb-chainsys/basicjava/src/edu/xml/jaxbLesson/purchaseorder.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://www.mybank.com/schema" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.mybank.com/schema" elementFormDefault="qualified">
	<xsd:element name="billingaddress">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="name"/>
				<xsd:element ref="street"/>
				<xsd:element ref="city"/>
				<xsd:element ref="state"/>
				<xsd:element ref="zip"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="city" type="xsd:string"/>
	<xsd:element name="date" type="xsd:string"/>
	<xsd:element name="description" type="xsd:string"/>
	<xsd:element name="identifier" type="xsd:string"/>
	<xsd:element name="item">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="quantity"/>
				<xsd:element ref="productnumber"/>
				<xsd:element ref="description"/>
				<xsd:element ref="unitcost"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="items">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="item" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="name" type="xsd:string"/>
	<xsd:element name="productnumber" type="xsd:string"/>
	<xsd:element name="purchaseorder">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="identifier"/>
				<xsd:element ref="date"/>
				<xsd:element ref="billingaddress"/>
				<xsd:element ref="items"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="quantity" type="xsd:int"/>
	<xsd:element name="state" type="xsd:string"/>
	<xsd:element name="street" type="xsd:string"/>
	<xsd:element name="unitcost" type="xsd:decimal"/>
	<xsd:element name="zip" type="xsd:string"/>
</xsd:schema>

=== vkrishnanb-chainsys/basicjava/src/edu/xml/jaxbLesson/purchaseorder.xml
<?xml version="1.0" encoding="UTF-8"?>
<purchaseorder xmlns="http://www.mybank.com/schema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:po="http://www.mybank.com/schema" xsi:schemaLocation="http://www.mybank.com/schema purchaseorder.xsd">
	<identifier>876564</identifier>
	<date>29 October 2002</date>
	<billingaddress>
		<name>John Malkovich</name>
		<street>256 Eight Bit Lane</street>
		<city>Burlington</city>
		<state>MA</state>
		<zip>01803-6326</zip>
	</billingaddress>
	<items>
		<item>
			<quantity>3</quantity>
			<productnumber>229AXH</productnumber>
			<description>High speed photocopier machine with automatic sensors</description>
			<unitcost>1939.99</unitcost>
		</item>
		<item>
			<quantity>1</quantity>
			<productnumber>1632</productnumber>
			<description>One box of color toner cartidges</description>
			<unitcost>43.95</unitcost>
		</item>
	</items>
</purchaseorder>
