=== vkrishnanb-chainsys/basicjava/src/edu/xml/domParser/address.dtd
<!ELEMENT Address (name+,phone,email) >
<!ELEMENT name (#PCDATA) >
<!ELEMENT phone (#PCDATA|mobile|land)* >
<!ELEMENT mobile (#PCDATA) >
<!ELEMENT land (#PCDATA) >
<!ELEMENT email EMPTY >
<!ATTLIST email id CDATA #REQUIRED
		aid CDATA #IMPLIED >
<!ATTLIST name type (first | middle | last) "first" >
<!ATTLIST phone city CDATA #FIXED "chennai" >

=== vkrishnanb-chainsys/basicjava/src/edu/xml/domParser/Address.xml
<?xml version='1.0'?>
<!DOCTYPE Address SYSTEM "address.dtd" >
<!-- Sample XML Page -->
<Address>
 	<name >venkat</name>
	<name type="last">Krishnan</name>
	<name type="middle">b</name>
	<phone>91-044
		<mobile>12321</mobile>
		<land>4	&lt; 1000
			<![CDATA[100<200 ]]>
		</land>
	</phone>
	<email id="a1@yahoo.com" aid="abc@xyz"/>
</Address>
